import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'title': 'SweatClock',
      'settings': 'Settings',
      'audio_feel': 'AUDIO & FEEL',
      'sound_effects': 'Sound Effects',
      'sound_effects_desc': 'Tones for phase transitions',
      'vibration': 'Vibration',
      'vibration_desc': 'Haptic feedback on ticks',
      'voice_cues': 'Voice Cues',
      'voice_cues_desc': 'Announce phase names',
      'countdown_vibration': 'Countdown Vibration',
      'countdown_vibration_desc': 'Vibrate on 3, 2, 1, Go',
      'display': 'DISPLAY',
      'dark_mode': 'Dark Mode',
      'dark_mode_desc': 'Cool neon dark palette',
      'keep_screen_on': 'Keep Screen On',
      'keep_screen_on_desc': 'Prevent auto sleep on timer',
      'general': 'GENERAL',
      'language': 'Language',
      'select_language': 'Select Language',
      'about_card_desc': 'Crafted with ❤️ for athletes and solo fitness enthusiasts worldwide.',
      'version': 'Version 1.0.0 (6)',
      'cancel': 'Cancel',
      'exit': 'Exit',
      'yes_exit': 'Yes, Exit',
      'exit_dialog_title': 'Exit Workout?',
      'exit_dialog_desc': 'Are you sure you want to stop this workout session? Your progress will be lost.',
      'preparation': 'Preparation',
      'workout': 'Workout',
      'rest': 'Rest',
      'rounds': 'Rounds',
      'total_time': 'Total Time',
      'start_workout': 'START WORKOUT',
      'resume': 'Resume',
      'pause': 'Pause',
      'skip': 'Skip',
      'reset': 'Reset',
      'congrats': 'Congratulations!',
      'congrats_desc': 'You finished your workout!',
      'home': 'Home',
      'buy_coffee': 'Support Developer',
      'small_coffee': 'Small Coffee',
      'coffee_donut': 'Coffee & Donut',
      'fuel_desc': 'Fuel a few coding hours & bug fixes.',
      'fuel_more_desc': 'Fuel design updates and feature work.',
      'seconds': 'seconds',
      'minutes': 'minutes',
      'stage': 'Stage',
      'set_time': 'Set Time',
      'set_rounds': 'Set Rounds',
      'done': 'Done',
    },
    'es': {
      'title': 'SweatClock',
      'settings': 'Ajustes',
      'audio_feel': 'AUDIO Y SENSACIÓN',
      'sound_effects': 'Efectos de Sonido',
      'sound_effects_desc': 'Tonos para transiciones de fase',
      'vibration': 'Vibración',
      'vibration_desc': 'Retroalimentación háptica',
      'voice_cues': 'Indicaciones de Voz',
      'voice_cues_desc': 'Anunciar nombres de fase',
      'countdown_vibration': 'Vibración de Cuenta Atrás',
      'countdown_vibration_desc': 'Vibrar en 3, 2, 1, ¡Ya!',
      'display': 'PANTALLA',
      'dark_mode': 'Modo Oscuro',
      'dark_mode_desc': 'Paleta oscura de neón',
      'keep_screen_on': 'Mantener Pantalla Activa',
      'keep_screen_on_desc': 'Evitar apagado de pantalla',
      'general': 'GENERAL',
      'language': 'Idioma',
      'select_language': 'Seleccionar Idioma',
      'about_card_desc': 'Creado con ❤️ para atletas y entusiastas del fitness en todo el mundo.',
      'version': 'Versión 1.0.0 (6)',
      'cancel': 'Cancelar',
      'exit': 'Salir',
      'yes_exit': 'Sí, Salir',
      'exit_dialog_title': '¿Salir del Entrenamiento?',
      'exit_dialog_desc': '¿Estás seguro de que quieres detener esta sesión? Se perderá tu progreso.',
      'preparation': 'Preparación',
      'workout': 'Entrenamiento',
      'rest': 'Descanso',
      'rounds': 'Rondas',
      'total_time': 'Tiempo Total',
      'start_workout': 'INICIAR ENTRENAMIENTO',
      'resume': 'Reanudar',
      'pause': 'Pausar',
      'skip': 'Omitir',
      'reset': 'Reiniciar',
      'congrats': '¡Felicidades!',
      'congrats_desc': '¡Terminaste tu entrenamiento!',
      'home': 'Inicio',
      'buy_coffee': 'Apoyar Creador',
      'small_coffee': 'Café Pequeño',
      'coffee_donut': 'Café y Dona',
      'fuel_desc': 'Apoya unas horas de código y solución de fallos.',
      'fuel_more_desc': 'Apoya actualizaciones de diseño y nuevas funciones.',
      'seconds': 'segundos',
      'minutes': 'minutos',
      'stage': 'Etapa',
      'set_time': 'Establecer Tiempo',
      'set_rounds': 'Establecer Rondas',
      'done': 'Listo',
    },
    'fr': {
      'title': 'SweatClock',
      'settings': 'Paramètres',
      'audio_feel': 'AUDIO & RESSENTI',
      'sound_effects': 'Effets Sonores',
      'sound_effects_desc': 'Tonalités pour les transitions',
      'vibration': 'Vibration',
      'vibration_desc': 'Retour haptique sur les ticks',
      'voice_cues': 'Indications Vocales',
      'voice_cues_desc': 'Annoncer les noms des phases',
      'countdown_vibration': 'Vibration Compte à Rebours',
      'countdown_vibration_desc': 'Vibrer sur 3, 2, 1, Go',
      'display': 'AFFICHAGE',
      'dark_mode': 'Mode Sombre',
      'dark_mode_desc': 'Palette sombre néon stylée',
      'keep_screen_on': 'Garder Écran Allumé',
      'keep_screen_on_desc': 'Empêcher la mise en veille',
      'general': 'GÉNÉRAL',
      'language': 'Langue',
      'select_language': 'Choisir la Langue',
      'about_card_desc': 'Créé avec ❤️ pour les athlètes et passionnés de fitness du monde entier.',
      'version': 'Version 1.0.0 (6)',
      'cancel': 'Annuler',
      'exit': 'Quitter',
      'yes_exit': 'Oui, Quitter',
      'exit_dialog_title': 'Quitter la Séance ?',
      'exit_dialog_desc': 'Êtes-vous sûr de vouloir arrêter la séance ? Votre progression sera perdue.',
      'preparation': 'Préparation',
      'workout': 'Entraînement',
      'rest': 'Repos',
      'rounds': 'Séries',
      'total_time': 'Temps Total',
      'start_workout': 'DÉMARRER LA SÉANCE',
      'resume': 'Reprendre',
      'pause': 'Pause',
      'skip': 'Passer',
      'reset': 'Réinitialiser',
      'congrats': 'Félicitations !',
      'congrats_desc': 'Vous avez fini votre entraînement !',
      'home': 'Accueil',
      'buy_coffee': 'Soutenir le Dév',
      'small_coffee': 'Petit Café',
      'coffee_donut': 'Café & Donut',
      'fuel_desc': 'Soutenir quelques heures de code et correctifs.',
      'fuel_more_desc': 'Soutenir les mises à jour et nouvelles fonctions.',
      'seconds': 'secondes',
      'minutes': 'minutes',
      'stage': 'Étape',
      'set_time': 'Régler le Temps',
      'set_rounds': 'Régler les Séries',
      'done': 'Valider',
    },
    'de': {
      'title': 'SweatClock',
      'settings': 'Einstellungen',
      'audio_feel': 'AUDIO & GEFÜHL',
      'sound_effects': 'Soundeffekte',
      'sound_effects_desc': 'Töne für Phasenübergänge',
      'vibration': 'Vibration',
      'vibration_desc': 'Haptisches Feedback bei Ticks',
      'voice_cues': 'Sprachanweisungen',
      'voice_cues_desc': 'Phasennamen ansagen',
      'countdown_vibration': 'Countdown-Vibration',
      'countdown_vibration_desc': 'Vibrieren bei 3, 2, 1, Los',
      'display': 'DISPLAY',
      'dark_mode': 'Dunkelmodus',
      'dark_mode_desc': 'Cooles Neon-Dunkel-Design',
      'keep_screen_on': 'Bildschirm eingeschaltet lassen',
      'keep_screen_on_desc': 'Automatischen Ruhezustand verhindern',
      'general': 'ALLGEMEIN',
      'language': 'Sprache',
      'select_language': 'Sprache auswählen',
      'about_card_desc': 'Mit ❤️ entwickelt für Athleten und Fitness-Begeisterte weltweit.',
      'version': 'Version 1.0.0 (6)',
      'cancel': 'Abbrechen',
      'exit': 'Beenden',
      'yes_exit': 'Ja, Beenden',
      'exit_dialog_title': 'Training beenden?',
      'exit_dialog_desc': 'Sind Sie sicher, dass Sie das Training abbrechen möchten? Ihr Fortschritt geht verloren.',
      'preparation': 'Vorbereitung',
      'workout': 'Training',
      'rest': 'Pause',
      'rounds': 'Runden',
      'total_time': 'Gesamtzeit',
      'start_workout': 'TRAINING STARTEN',
      'resume': 'Fortsetzen',
      'pause': 'Pause',
      'skip': 'Überspringen',
      'reset': 'Zurücksetzen',
      'congrats': 'Herzlichen Glückwunsch!',
      'congrats_desc': 'Du hast dein Training beendet!',
      'home': 'Start',
      'buy_coffee': 'Entwickler unterstützen',
      'small_coffee': 'Kleiner Kaffee',
      'coffee_donut': 'Kaffee & Donut',
      'fuel_desc': 'Unterstützt ein paar Stunden Code & Bugfixes.',
      'fuel_more_desc': 'Unterstützt Design-Updates und neue Features.',
      'seconds': 'Sekunden',
      'minutes': 'Minuten',
      'stage': 'Stufe',
      'set_time': 'Zeit einstellen',
      'set_rounds': 'Runden einstellen',
      'done': 'Fertig',
    },
    'ja': {
      'title': 'SweatClock',
      'settings': '設定',
      'audio_feel': 'オーディオと触覚',
      'sound_effects': '効果音',
      'sound_effects_desc': 'フェーズ切り替え音',
      'vibration': 'バイブレーション',
      'vibration_desc': 'カウント時の振動フィードバック',
      'voice_cues': '音声ガイダンス',
      'voice_cues_desc': 'フェーズ名を音声でお知らせ',
      'countdown_vibration': 'カウントダウンの振動',
      'countdown_vibration_desc': '3、2、1、開始時に振動する',
      'display': 'ディスプレイ',
      'dark_mode': 'ダークモード',
      'dark_mode_desc': 'クールなネオンダークテーマ',
      'keep_screen_on': '画面の常時点灯',
      'keep_screen_on_desc': 'タイマー作動中の自動スリープ防止',
      'general': '全般',
      'language': '言語',
      'select_language': '言語を選択',
      'about_card_desc': '世界中のアスリートとフィットネス愛好家のために ❤️ を込めて作成されました。',
      'version': 'バージョン 1.0.0 (6)',
      'cancel': 'キャンセル',
      'exit': '終了',
      'yes_exit': 'はい、終了します',
      'exit_dialog_title': 'ワークアウトを終了しますか？',
      'exit_dialog_desc': 'ワークアウトを停止しますか？ここまでの進行状況は失われます。',
      'preparation': '準備',
      'workout': 'ワークアウト',
      'rest': '休憩',
      'rounds': 'ラウンド数',
      'total_time': '合計時間',
      'start_workout': 'ワークアウトを開始',
      'resume': '再開',
      'pause': '一時停止',
      'skip': 'スキップ',
      'reset': 'リセット',
      'congrats': 'お疲れ様でした！',
      'congrats_desc': 'ワークアウトを完了しました！',
      'home': 'ホーム',
      'buy_coffee': '開発者を支援',
      'small_coffee': 'コーヒーを奢る',
      'coffee_donut': 'コーヒーとドーナツ',
      'fuel_desc': 'コーディングとバグ修正を支援します。',
      'fuel_more_desc': 'デザインと新機能の開発を支援します。',
      'seconds': '秒',
      'minutes': '分',
      'stage': 'ステージ',
      'set_time': '時間を設定',
      'set_rounds': 'ラウンドを設定',
      'done': '完了',
    },
    'hi': {
      'title': 'SweatClock',
      'settings': 'सेटिंग्स',
      'audio_feel': 'ऑडियो और वाइब्रेशन',
      'sound_effects': 'ध्वनि प्रभाव',
      'sound_effects_desc': 'चरणों के बदलाव पर टोन बजाएं',
      'vibration': 'कंपन (वाइब्रेशन)',
      'vibration_desc': 'टिक-टिक होने पर हैप्टिक कंपन',
      'voice_cues': 'आवाज संकेत',
      'voice_cues_desc': 'चरणों के नाम की घोषणा करें',
      'countdown_vibration': 'काउंटडाउन वाइब्रेशन',
      'countdown_vibration_desc': '3, 2, 1, गो पर कंपन करें',
      'display': 'डिस्प्ले',
      'dark_mode': 'डार्क मोड',
      'dark_mode_desc': 'कूल नियॉन डार्क थीम',
      'keep_screen_on': 'स्क्रीन चालू रखें',
      'keep_screen_on_desc': 'टाइमर चलते समय स्क्रीन बंद न होने दें',
      'general': 'सामान्य',
      'language': 'भाषा',
      'select_language': 'भाषा चुनें',
      'about_card_desc': 'दुनिया भर के एथलीटों और फिटनेस प्रेमियों के लिए ❤️ के साथ बनाया गया है।',
      'version': 'संस्करण 1.0.0 (6)',
      'cancel': 'रद्द करें',
      'exit': 'बाहर जाएं',
      'yes_exit': 'हां, बाहर जाएं',
      'exit_dialog_title': 'वर्कआउट बंद करें?',
      'exit_dialog_desc': 'क्या आप सच में वर्कआउट बंद करना चाहते हैं? आपकी प्रगति खो जाएगी।',
      'preparation': 'तैयारी',
      'workout': 'वर्कआउट',
      'rest': 'आराम',
      'rounds': 'राउंड',
      'total_time': 'कुल समय',
      'start_workout': 'वर्कआउट शुरू करें',
      'resume': 'जारी रखें',
      'pause': 'रोकें',
      'skip': 'छोड़ें',
      'reset': 'रीसेट करें',
      'congrats': 'बधाई हो!',
      'congrats_desc': 'आपने अपना वर्कआउट पूरा कर लिया!',
      'home': 'होम',
      'buy_coffee': 'डेवलपर का समर्थन करें',
      'small_coffee': 'छोटी कॉफ़ी',
      'coffee_donut': 'कॉफ़ी और डोनट',
      'fuel_desc': 'कुछ घंटे कोडिंग और बग ठीक करने में मदद करें।',
      'fuel_more_desc': 'डिजाइन अपडेट और नए फीचर्स में मदद करें।',
      'seconds': 'सेकंड',
      'minutes': 'मिनट',
      'stage': 'चरण',
      'set_time': 'समय सेट करें',
      'set_rounds': 'राउंड सेट करें',
      'done': 'हो गया',
    }
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'es', 'fr', 'de', 'ja', 'hi'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
